### ISSUE TITLE
Coundn't  found  CustomNetwork for network wich Tried to  python main.py  

### ISSUE THREAD

**Issue by molyswu** [dddzg/MoCo#1]
Hi，

  Tried to python main.py 
   from network import CustomNetwork, Net

ImportError: cannot import name 'CustomNetwork' from 'network'

Tried to pip install network ,It didn't worked .

Thanks

**Comment by dddzg** [comment]
Thanks for your issue. I forgot to upload the network.py file. CustomNetwork is not used in the code, so you can delete this line.
